kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
      systemReserved:
        cpu: 200m
        memory: 500Mi
      kubeReserved:
        cpu: 100m
        memory: 250Mi
  - |
    kind: ClusterConfiguration
    controllerManagerExtraArgs:
      horizontal-pod-autoscaler-use-rest-clients: "true"
    apiServerExtraArgs:
      runtime-config: "api/all=true"
    admissionConfiguration:
      enabled: false
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
      systemReserved:
        cpu: 200m
        memory: 500Mi
      kubeReserved:
        cpu: 100m
        memory: 250Mi
