image:
  source: kousik93/simple-dump-server:assignment-test
  pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "300m"
      memory: "150Mi"
    requests:
      cpu: "200m"
      memory: "100Mi"

ingress:
  fqdn:
  class: nginx
  certSecretName:
  affinity: ''
enableMonitoring: false
