---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-dump-server
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
  annotations:
    "service-version": {{ .Chart.AppVersion | quote }}
  name: simple-dump-server
spec:
  selector:
      matchLabels:
        app: simple-dump-server
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote}}
        release: {{.Release.Name | quote}}
        chart: {{ .Chart.Name }}
        app: simple-dump-server
    spec:
      serviceAccountName: simple-dump-server
      containers:
      - name: simple-dump-server
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 20      
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 20
          periodSeconds: 30
        image: {{required ".Values.image.source is required" .Values.image.source }}       
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.image.resources | indent 10 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
