apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-dump-server
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
  annotations:
    prometheus.io/scrape: "true"
  name: simple-dump-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: simple-dump-server
  sessionAffinity: None
  type: ClusterIP 
